### PR TITLE
New website design

### PR DESCRIPTION
**Pull request by diazvictor**
For the moment I have omitted content from the previous template with the intention of integrating it while the rest of the layout is being assembled. This is something I will be doing over time (I don't plan to take too long).

This is just a mockup, so I commented some of the php code because of what I said above.

### CODE REVIEW

**Comment by hwspeedy** [comment]
@diazvictor 

I have changed the server www to show you a vanillaJS example - I see the previous parking index.php was not helping. Sorry. :)

1. Changed index.php - Don't worry about this part - it's the application API.
2. Added a simple www API - see www/api/gethtmltables
3. Changed the initial page to VanillaJS to be used as an example - see www/index.html and www/js/example.js.

**So please put your contribution in www/new1/:**
 - www/new1/index.html
 - www/new1/js/...
 - www/new1/css/...
 - www/new1/...

Your site idea 1 - should then be accessible by https://hardinfo2.org/new1/   (When changed and I commit it)

Other ideas can then be put into new2, new3 etc.

@mckaygerhard - Maybe mckaygerhard will coordinate and write some explaining information about the last part for the contest in discussion, thanx.

PS: Just to clarify - there is no PHP in frontend design. PHP is only for the backend API and application API.

PPS: No inline javascript - use addEventListener and put all javascript in .js files.

**Comment by mckaygerhard** [comment]
wow! movin files in the era of git management!

**Comment by hwspeedy** [comment]
@diazvictor 

Please update PR - people are starting to notice hardinfo2 community release.
Unmix front-end from back-end as written above and put into new1, thanx.
There are some examples with graph.js, if you would like to add that. - see bottom of https://hardinfo2.org
Before we can switch it needs to have at least some content.

@mckaygerhard 
We need to have it deployed on the server to test how it looks and feels on phones, tablets, PC's etc.
Can you check content for correct license of pictures, fonts, etc. and guide him, thanx.

**PS: Website design is open for everyone - just make a PR or write in [hardinfo2/discussion ](https://github.com/hardinfo2/hardinfo2/discussions) about the interest and you will get an invite to join the organization, thanx**

**Comment by mckaygerhard** [comment]
i guess he lost the interest becouse you are using too old tech behaviour.. 

i fact he was talking about sqlite that dont need too complicated deploy with mysql.. inclusivelly we can use a free mongodb node

**Comment by hwspeedy** [comment]
@mckaygerhard 
I am starting to get the feeling, that you totally have lost it. 

Are you sure, that you want to be part of hardinfo2 community edition?

CC: @lpereira

**Pull request closed without merging**
